INSERT INTO role (name) SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='ADMIN');
INSERT INTO role (name) SELECT 'EMPLOYEE' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='EMPLOYEE');
INSERT INTO role (name) SELECT 'USER' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='USER');
INSERT INTO role (name) SELECT 'HR' WHERE NOT EXISTS (SELECT 1 FROM role WHERE name='HR');